function exercise1()
{
  document.write("<table style='border: solid 2px;'>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Свойство </td>");
  document.write("<td style='border:solid 1px;'> Значение </td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Информация о браузере:  </td>");
  document.write("<td style='border:solid 1px;'>" + navigator.userAgent + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Версия браузера: </td>");
  document.write("<td style='border:solid 1px;'>" + navigator.appVersion + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Название браузера: </td>");
  document.write("<td style='border:solid 1px;'>" + navigator.appName + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Кодовое название браузера: </td>");
  document.write("<td style='border:solid 1px;'>" + navigator.appCodeName + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> ОС, которую использует браузер: </td>");
  document.write("<td style='border:solid 1px;'>" + navigator.platform + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Включена ли поддержка Java в браузере пользователя или нет: </td>");
  document.write("<td style='border:solid 1px;'>" + window.navigator.javaEnabled() + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Ширина экрана пользователя: </td>");
  document.write("<td style='border:solid 1px;'>" + screen.width + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Высота экрана пользователя: </td>");
  document.write("<td style='border:solid 1px;'>" + screen.height + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Глубина экрана пользователя: </td>");
  document.write("<td style='border:solid 1px;'>" + screen.colorDepth + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> URL, которые были посещены в данном окне браузера: </td>");
  document.write("<td style='border:solid 1px;'>" + history.length + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> URL текущего документа: </td>");
  document.write("<td style='border:solid 1px;'>" + location.href + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Путь к загруженному документу: </td>");
  document.write("<td style='border:solid 1px;'>" + location.pathnam + "</td>");
  document.write("</tr>");
  document.write("<tr>");
  document.write("<td style='border:solid 1px;'> Имя домена загруженного документа: </td>");
  document.write("<td style='border:solid 1px;'>" + location.host + "</td>");
  document.write("</tr>");
}
